### ISSUE TITLE
Add Title

### ISSUE THREAD

**Issue by jaiyankargupta** [Mohak1809/OCD-Website#1]
Add title of the website

**Comment by jaiyankargupta** [comment]
please assign me this project

**Comment by Abhaykumar212** [comment]
@jaiyankargupta please assign this issue to me

**Comment by jaiyankargupta** [comment]
@Abhaykumar212 okay

**Comment by jaiyankargupta** [comment]
@Abhaykumar212 please send pull request

**Comment by MaulikGupta27** [comment]
@Mohak1809 please assign this issue to me

**Comment by jaiyankargupta** [comment]
@MaulikGupta27 request for another issue. ye assign hain abhay ko

**Comment by Abhaykumar212** [comment]
> @Abhaykumar212 please send pull request

kr dia tha bhaiya
