### ISSUE TITLE
Add social media handles to connect

### ISSUE THREAD

**Issue by Codecoder27** [Mohak1809/OCD-Website#10]
- DESCRIPTION: It would be great to add social media handles on the website for people to connect in case of queries or suggestions. 
- Connecting with users would let us get feedback and improve functioning of the website.

**Comment by Khushi-S-29** [comment]
@Mohak1809 Please assign this issue to me

**Comment by Mohak1809** [comment]
@Khushi-S-29 okay

**Comment by jaiyankargupta** [comment]
@Khushi-S-29 please send PR
