### ISSUE TITLE
Create Placeholder Content for Project Showcases

### ISSUE THREAD

**Issue by Khushi-S-29** [Mohak1809/OCD-Website#12]
Create placeholder content for each project:
 * Add placeholder titles for projects.
* Write brief descriptions summarizing each project's purpose and key features.
* Include placeholders for images or graphics.
* Prepare placeholders for links to relevant URLs.

**Expected Outcome**
A well-structured project showcase section with placeholders for each project, ready to be populated with detailed content as it becomes available.

**Comment by Aastha304** [comment]
@Khushi-S-29 , I would like to do these modifications.

**Comment by jaiyankargupta** [comment]
@Aastha304 done
