### ISSUE TITLE
Create a search bar and add placeholder text

### ISSUE THREAD

**Issue by Malavika-Gupta** [Mohak1809/OCD-Website#13]
**Objective:**
Enhance the search functionality by adding search bar.

**Description**

1. Create HTML Search Bar and Implement an <input> element of type "text".
2. Add placeholder text to the input field to indicate its use.
3. Use CSS to style the search bar.
4. Verify that the placeholder text is visible and displays correctly.

**Comment by jackabald** [comment]
Hey!

I would like to work on this issue. Is anyone else working on it?

**Comment by DeadpoolX7** [comment]
I am willing to undertake this task and meet the following requirements.

Assign me this issue to resolve.

**Comment by jaiyankargupta** [comment]
@jackabald done, now you can resolve the issue and send pull request

**Comment by jackabald** [comment]
@jaiyankargupta I sent a pull request. Please let me know if this fits your needs :)

**Comment by jaiyankargupta** [comment]
@jackabald merged, please create another issues too.
