### ISSUE TITLE
reset button in login page

### ISSUE THREAD

**Issue by Sahil-Bhardwaj29** [Mohak1809/OCD-Website#136]
The reset button in a login page is used to reset the form fields to their initial values. It is typically used when a user wants to clear the form and start over.
When you click the reset button, it will clear the text field and reset it to its initial value.

**Comment by Sahil-Bhardwaj29** [comment]
@Mohak1809 please assign this issue to me

**Comment by jaiyankargupta** [comment]
@Sahil-Bhardwaj29 done
