### ISSUE TITLE
 Implement Smooth Scrolling for Navigation Links

### ISSUE THREAD

**Issue by harshtiwari1412** [Mohak1809/OCD-Website#139]
Description:
- Currently, clicking on navigation links instantly jumps to the respective section on the page. Adding a smooth scrolling effect would enhance the user experience by making the transition more visually appealing.

Steps to Reproduce:
- Click on any navigation link in the header.
- Notice the instant jump to the section without any smooth transition.

Suggested Fix:
- Add CSS or JavaScript to enable smooth scrolling for navigation links. For example, in CSS, you can add scroll-behavior: smooth; to the html element.

**Comment by NavvneetK** [comment]
@jaiyankargupta assign this issue to me

**Comment by jaiyankargupta** [comment]
@NavvneetK done
