### ISSUE TITLE
Navbar is not responsive

### ISSUE THREAD

**Issue by NitikaSheoran** [Mohak1809/OCD-Website#167]
Navbar is not responsive according to size of the screen. If screen size gets smaller it gets distorted and few of the elements are not visible

*Suggestion*: You can use the @media queries to specific screen sizes depending on your design needs.

**Comment by BitByteBoss** [comment]
@jaiyankargupta  assign this issue to me

**Comment by NitikaSheoran** [comment]
@jaiyankargupta assign this issue to me

**Comment by jaiyankargupta** [comment]
@NitikaSheoran done
