### ISSUE TITLE
Alert on successful submission

### ISSUE THREAD

**Issue by piyushnitkkr** [Mohak1809/OCD-Website#17]
### **Alert on successful submission**

The contact form on the OCD Society NIT KKR website does not provide user feedback upon successful submission. This can confuse users, leaving them uncertain if their message has been sent.

- Implement a JavaScript alert or message display that confirms the form submission.

**Comment by piyushnitkkr** [comment]
@Mohak1809 assign this issue to me

**Comment by DivyanshuK2133** [comment]
@Mohak1809  please assign this issue to me

**Comment by jaiyankargupta** [comment]
@piyushnitkkr assign kar diya hain , ab aap issue ko resolve kare and pull request kare.

**Comment by jaiyankargupta** [comment]
@DivyanshuK2133 dude, ek issue ke liye hi request karni hain. And tab tak wait karni hain jab tak approval na mile

**Comment by piyushnitkkr** [comment]
@jaiyankargupta  done

**Comment by jaiyankargupta** [comment]
@piyushnitkkr merged
