### ISSUE TITLE
add about section

### ISSUE THREAD

**Issue by anshikaa13** [Mohak1809/OCD-Website#18]
It will be good to tell users about what our society do. we can also describe our OCD community groups  as in each group we do different tasks.

- in HTML body add about section

**Comment by pragya174** [comment]
@anshikaa13 please assign this issue to me.

**Comment by gargDhruv12** [comment]
@Mohak1809 Please assign this task to me

**Comment by jaiyankargupta** [comment]
@pragya174 done, now you can resolve the issue and send a pull request

**Comment by jaiyankargupta** [comment]
@gargDhruv12 dude, go to another issue.

**Comment by gargDhruv12** [comment]
> @gargDhruv12 dude, go to another issue.

Okay sir
