### ISSUE TITLE
Create Navbar Section

### ISSUE THREAD

**Issue by jaiyankargupta** [Mohak1809/OCD-Website#2]
The navbar should include sections for Home, About Us, Projects, and Blogs. It needs to be responsive and user-friendly across different devices.

**Steps to Reproduce:**

- Create a basic HTML structure for the navbar.
- Add links for Home, About Us, Projects, and Blogs.
- Apply CSS for styling.
- Ensure responsiveness using media queries

**Comment by Codecoder27** [comment]
@Mohak1809 please assign this issue to me.

**Comment by jaiyankargupta** [comment]
@Codecoder27 okay

**Comment by jaiyankargupta** [comment]
@Codecoder27 please send pull request.
