### ISSUE TITLE
 Footer Position Improvement in Resource Library

### ISSUE THREAD

**Issue by rajveerpathak1** [Mohak1809/OCD-Website#202]
Currently, when the options to select 1. Add resources or 2. View resources are shown in the Resource Library, the footer is not positioned appropriately. This affects the overall user experience, making the interface appear cluttered and less user-friendly.

1. Proposed Improvement:
Adjust the footer positioning to ensure it remains at the bottom of the viewport regardless of the content displayed above it. This will create a cleaner and more consistent user experience.

2.Ensure the footer remains responsive and maintains its position across different screen sizes and devices.
Consider adding CSS adjustments to handle dynamic content changes within the Resource Library section.

3.Expected Outcome:
The footer should be fixed at the bottom of the viewport, providing a consistent layout and ensuring that the selection options are clearly visible without affecting the footer's position.

4.Current Outcome:
The footer appears to be misaligned or positioned awkwardly when the options to select resources are displayed.

**Comment by NikhilByteSmith** [comment]
@jaiyankargupta please assign this issue to me

**Comment by NikhilByteSmith** [comment]
@jaiyankargupta please assign this issue to me

**Comment by jaiyankargupta** [comment]
@NikhilByteSmith done
