### ISSUE TITLE
Create CAPTCHA during login

### ISSUE THREAD

**Issue by AyushAntil007** [Mohak1809/OCD-Website#21]
The login page will ask the basic information like username, password , etc. and after filling all details it will generate a CAPTCHA ,to check whether the user is human or AI.

Steps to reproduce:

- Create username, password ,CAPTCHA entry box using input element in html.
- Create Refresh and Login button
- Do styling of the login page using html
- And for CAPTCHA generation we can use random module to auto generate new CAPTCHA on refreshing.
- Once the CAPTCHA is verified click on login button and we will be directed to our website.

**Comment by Kharb-Hardik** [comment]
pls assign this issue to me

**Comment by jaiyankargupta** [comment]
@Kharb-Hardik done
