### ISSUE TITLE
Making OCD logo and Providing social media handles 

### ISSUE THREAD

**Issue by Sameer-0001** [Mohak1809/OCD-Website#22]
Improvement can be done by :-

Providing online links of OCD Social media handles in the bottom of page

Adding animation in font or Adding animating Background of OCD logo and choosing right color combination, so that text can be visible as well as  boost web page.

Making OCD logo and Adding it with Header

**Comment by DivyanshuK2133** [comment]
Please assign this issue to me

**Comment by jaiyankargupta** [comment]
@DivyanshuK2133 done

**Comment by DivyanshuK2133** [comment]
I have created the pull request
