### ISSUE TITLE
No headings in ~Our Programs ~ cards

### ISSUE THREAD

**Issue by Aastha304** [Mohak1809/OCD-Website#224]
Issue: 

- The different program cards look undescriptive and does not grab attention.
- The user should be able to understand each component of a website at a glance.

**The modifications will help the website look more understandable about its content and hence enhancing users experience.**

**Comment by jaiyankargupta** [comment]
@Aastha304 can i assign you ??

**Comment by Rkgarg2127** [comment]
please assign me.

**Comment by jaiyankargupta** [comment]
@Rkgarg2127 done
