### ISSUE TITLE
Adding Hero section

### ISSUE THREAD

**Issue by gargDhruv12** [Mohak1809/OCD-Website#23]
**Hero section is the prominent introductory section of a website
It conveys the main message of the website** 

- A high quality image can be added that describe website's theme/ or video may be 
- A attention grabbing headline and quote
- Transition effects can be added to make it more attractive
- If needed a sign up button can also be added here or a button can be created for any other important action that redirects to some link or other section

**Comment by Kaushi-vashisth** [comment]
@gargDhruv12 Kindly assign this to me

**Comment by gargDhruv12** [comment]
I think you should tag Rahul sir ,only he can assign

**Comment by Kaushi-vashisth** [comment]
@jaiyankargupta Kindly assign this to me

**Comment by jaiyankargupta** [comment]
@Kaushi-vashisth done
