### ISSUE TITLE
Add Login page for the user

### ISSUE THREAD

**Issue by pragya174** [Mohak1809/OCD-Website#24]
A Login page should include username, password and login button.

**Steps :**
- Create an HTML form for the login page.
- Apply CSS to style the login page.
- Add input element for username, password with placeholder and button for login.

**Comment by DivyanshuK2133** [comment]
@Mohak1809 @pragya174    Please assign this issue to me

**Comment by jaiyankargupta** [comment]
@DivyanshuK2133 done

**Comment by Sonia2105** [comment]
@Mohak1809 please assign this issue to me

**Comment by nototiger0227** [comment]
@jaiyankargupta Please assign this issue to me.

**Comment by jaiyankargupta** [comment]
@Sonia2105 done

**Comment by jaiyankargupta** [comment]
@nototiger0227 dusra issue pick Karo, ye assign hain kisi ko
