### ISSUE TITLE
Dark mode issue 

### ISSUE THREAD

**Issue by NikhilByteSmith** [Mohak1809/OCD-Website#244]
In dark mode in our programs section, the heading of the cards disappears 
normal mode
![image](https://github.com/user-attachments/assets/0db578fe-39bd-4579-9bd3-170f0a330359)
dark mode
DSA              COMPETITIVE PROGRAMING30              DAYS OF JS not visible
![image](https://github.com/user-attachments/assets/eb734a66-2f33-4834-95db-672479b575f4)

**Comment by Isham17NIT** [comment]
@jaiyankargupta pls assign this issue to me

**Comment by jaiyankargupta** [comment]
@Isham17NIT resolved
