### ISSUE TITLE
Improve CSS of Feedback Page

### ISSUE THREAD

**Issue by Palak565** [Mohak1809/OCD-Website#256]
Improve CSS of **Feedback Page**. 
Issues to be resolved:

- Search icon is out of search bar & covers almost half of the screen. 
- OCD logo is very big.
- Unnecessary **Help Us Improve** link on the feedback page itself, which redirects to the same page.
- Footer is not organised.
- Navbar is not styled.
- Dark mode not working.

**Comment by Isham17NIT** [comment]
@jaiyankargupta pls assign this issue to me.

**Comment by jaiyankargupta** [comment]
@Isham17NIT assigned
