### ISSUE TITLE
Improve the Links Navbar

### ISSUE THREAD

**Issue by jaiyankargupta** [Mohak1809/OCD-Website#263]
**Improve the Link Navbar**

- all links should be working
- when i click to **links**, it should be open in same page
- improve the links dropdown, like checks all links is working or not and make sure check in dark mode also, if it is not visible, make it visible

**Comment by jaiyankargupta** [comment]
![Uploading Screenshot 2024-07-22 at 2.42.50 PM.png…]()

**Comment by anshikaa13** [comment]
@jaiyankargupta pls assign this to me

**Comment by jaiyankargupta** [comment]
@anshikaa13 done
