### ISSUE TITLE
Make PopUp Responsive 

### ISSUE THREAD

**Issue by jaiyankargupta** [Mohak1809/OCD-Website#267]
**Make PopUp Responsive** 

- when screen size is changing then join button is not show better.

<img width="1280" alt="Screenshot 2024-07-22 at 2 40 23 PM" src="https://github.com/user-attachments/assets/f2238f43-475d-431a-afe7-8bd2d2634314">

**Comment by Sonia2105** [comment]
Please assign this task to me

**Comment by jaiyankargupta** [comment]
@Sonia2105 done
