### ISSUE TITLE
Home link on About us Page not working

### ISSUE THREAD

**Issue by rare20** [Mohak1809/OCD-Website#269]
on clicking on Home in the navbar section on About us Page it is not landing on the Home page and showing the error

so redirect the link of the home page to the option of Home in navbar section

**Comment by anshika494** [comment]
@jaiyankargupta plz assign this issue to me

**Comment by jaiyankargupta** [comment]
@rare20 ispe koi work kar raha hain, aap bne huye issues dekhlo, fir issue create kro

**Comment by jaiyankargupta** [comment]
@anshika494 koi dusra issue choose kro
