### ISSUE TITLE
Home button not redirecting to home page, displays 404 error

### ISSUE THREAD

**Issue by Aarsh13** [Mohak1809/OCD-Website#281]
**Description**:
When clicking the home button after navigating to any other page, the user is not redirected to the home page as expected. Instead, a 404 "File not found" error page is displayed.

**Steps to reproduce:**

- Navigate to any page on the site
- Click the home button
- Observe the resulting page

**Expected behavior:**
The user should be redirected to the home page

**Actual behavior:**
A 404 error page is displayed with the message "File not found"

![image](https://github.com/user-attachments/assets/b38bb606-9c54-4a60-bda9-c7a67f21ab73)

**Comment by jaiyankargupta** [comment]
@Aarsh13 issues pahle se bn rakhe hain, check to krlo
