### ISSUE TITLE
Improve Contributors page in both modes

### ISSUE THREAD

**Issue by MaulikGupta27** [Mohak1809/OCD-Website#287]
The CSS of the Contributors page needs to be corrected in both light and dark mode.

![image](https://github.com/user-attachments/assets/b53ba7d4-479a-4d03-a3bf-dec413b82381)

**Comment by anshikaa13** [comment]
@jaiyankargupta pls assign this task to me

**Comment by jaiyankargupta** [comment]
@MaulikGupta27 ye issue availble hain

**Comment by jaiyankargupta** [comment]
@anshikaa13 @MaulikGupta27 check krlo, issue no - #273

**Comment by MaulikGupta27** [comment]
@anshikaa13 @jaiyankargupta updated the issue...pls check

**Comment by jaiyankargupta** [comment]
@MaulikGupta27 create new issue, and close this issue
