### ISSUE TITLE
Some issue in styling of dark mode.

### ISSUE THREAD

**Issue by SanjayGrover** [Mohak1809/OCD-Website#299]
While using dark mode the program cards has a different shade for headings background which is unnecessary.
![Before - Current State](https://github.com/user-attachments/assets/b3ef95b8-87b9-4d09-a949-8ce3dca95ab1)
And after removing that particular css it looks like.
![After - Final State](https://github.com/user-attachments/assets/0d993b43-84a9-4bab-a9d7-34f37c548a18)
which is better according to me.

**Comment by SanjayGrover** [comment]
@jaiyankargupta Let me handle this issue.

**Comment by jaiyankargupta** [comment]
@SanjayGrover already fixed, checkout website
