### ISSUE TITLE
Add contact page for user

### ISSUE THREAD

**Issue by divyadahiya14** [Mohak1809/OCD-Website#31]
this page should include information columns for Name , email ID, phone no. , and message box for suggestion and questions user want to ask 

- html of page
- CSS of page

**Comment by Vkgupta18** [comment]
@divyadahiya14 I would like to work on it

**Comment by jaiyankargupta** [comment]
@Vkgupta18 please tag me

**Comment by Vkgupta18** [comment]
@jaiyankargupta please assign this task to me

**Comment by jaiyankargupta** [comment]
@Vkgupta18 done, now you can resolve the issue and send a pull request
