### ISSUE TITLE
CSS not visible in Join_30DayOfJs.html 

### ISSUE THREAD

**Issue by yash-shakya** [Mohak1809/OCD-Website#310]
![Screenshot (10)](https://github.com/user-attachments/assets/fb92f322-d1e6-4271-bea9-83333eb3732c)
css of the join_30DayOfJs.html is not visible on the website, but it works fine while using with live server

**Comment by ANUBHAVDIXIT2004** [comment]
pls assign this issue to me @jaiyankargupta

**Comment by jaiyankargupta** [comment]
@ANUBHAVDIXIT2004 done
