### ISSUE TITLE
Font size of navbar and Hover  effect

### ISSUE THREAD

**Issue by shakshiyadav14** [Mohak1809/OCD-Website#311]
1)Reduce the font size of all navbar headings and dropdown links.

2)The hover effect value is too high on the social media logos (so please reduce it to be more visually pleasing).

![Screenshot 2024-07-22 205445](https://github.com/user-attachments/assets/b7172665-88f4-42d4-a005-ef2b66928b48)
![Screenshot 2024-07-22 210400](https://github.com/user-attachments/assets/11c86faf-c892-4201-a156-95da14f865c5)

**Comment by jaiyankargupta** [comment]
@AyushAntil007 done
