### ISSUE TITLE
Footer Links Not Working - 404 Error

### ISSUE THREAD

**Issue by Tanisha020** [Mohak1809/OCD-Website#318]
The footer links on the entire website are not functioning correctly. Clicking on any footer link results in a **404 error**, preventing navigation to the intended pages.

- Verify that the URLs for the footer links are correctly configured across all pages.
- Ensure that the target pages for these links exist and are accessible.
- Check for any recent changes or updates that might have impacted the footer link functionality site-wide.
- Inspect the footer's HTML and routing configurations to ensure there are no errors.
![Screenshot 2024-07-22 220855](https://github.com/user-attachments/assets/7960064a-b816-44b4-ac74-0cbfeec6a903)

**Comment by yashika1221** [comment]
@jaiyankargupta assign this to me

**Comment by Sahil-Bhardwaj29** [comment]
@Mohak1809 sir please it to me

**Comment by jaiyankargupta** [comment]
@Sahil-Bhardwaj29 @Tanisha020 i think, ye fixed ho gya hain, check it

**Comment by Tanisha020** [comment]
@jaiyankargupta yes its working now.
