### ISSUE TITLE
Feedback section 

### ISSUE THREAD

**Issue by rishabhchaudhary2** [Mohak1809/OCD-Website#32]
***Implement a feedback form or comment section to gather user opinions and suggestions.***

->It could be a text area  or can be a feedback form
->should be at the end 
->also added to navbar

**Comment by Malavika-Gupta** [comment]
@jaiyankargupta Please assign me this issue.

**Comment by jaiyankargupta** [comment]
@Malavika-Gupta done, please resolve this issue and send a pull request
