### ISSUE TITLE
Improve CSS of program cards

### ISSUE THREAD

**Issue by Isham17NIT** [Mohak1809/OCD-Website#328]
https://github.com/user-attachments/assets/985f1771-a00a-463e-b57c-ebe670743d93
The CSS of the program cards especially the alignment of buttons(Learn More) can be improved since they are touching the bottom of that particular div.

**Comment by Isham17NIT** [comment]
@jaiyankargupta pls assign this issue to me

**Comment by MaulikGupta27** [comment]
@jaiyankargupta please assign this issue to me

**Comment by jaiyankargupta** [comment]
@Isham17NIT done
