### ISSUE TITLE
Title of Contest page in dark mode

### ISSUE THREAD

**Issue by MaulikGupta27** [Mohak1809/OCD-Website#330]
The "UPCOMING CODING CONTEST" title of contest page is not visible in the dark mode. Correct it.
![image](https://github.com/user-attachments/assets/b30c8b3b-829b-431a-853e-1fa3c622a96d)

**Comment by ANUBHAVDIXIT2004** [comment]
@jaiyankargupta pls assign this to me

**Comment by rajveerpathak1** [comment]
assign it to me

**Comment by anshikaa13** [comment]
I have made pull request for it waiting for merge
