### ISSUE TITLE
Enhancing the feedback page

### ISSUE THREAD

**Issue by Senpenn** [Mohak1809/OCD-Website#344]
![Screenshot 2024-07-23 154029](https://github.com/user-attachments/assets/e9316423-df3a-4eab-a9f6-140bc1ee8d07)
as you can see,the logo isn't visible and things look a bit out of place,we can  align sections better and maybe reduce the size of ocd picture and make it look more visually appealing.

**Comment by Aarsh13** [comment]
@jaiyankargupta Please assign this issue to me

**Comment by rishabhchaudhary2** [comment]
the css is connected the only problem is with ocd logo in footer section 
<img width="1434" alt="Screenshot 2024-07-23 at 4 35 33 PM" src="https://github.com/user-attachments/assets/d357fba2-c9cc-4b4f-a9b7-f4fe36b90656">

@jaiyankargupta assign this task to me.

**Comment by jaiyankargupta** [comment]
@rishabhchaudhary2 bhai website pe dekh, nhi chal raha hain

**Comment by jaiyankargupta** [comment]
@rishabhchaudhary2 done
