### ISSUE TITLE
Improve Styling & add projects

### ISSUE THREAD

**Issue by Palak565** [Mohak1809/OCD-Website#35]
The web page if styled in a better way may attract a lot of coding enthusiasts as it will build their confidence on the website. 
- OCD logo can be added.
- Different color combinations can be used to make it more lively.

The more website will be organised, coders will be easily able to find if their interests match & join with the amazing community.
Morever, add current & future projects to be worked upon.

**Comment by MaulikGupta27** [comment]
@Mohak1809 please assign this to me

**Comment by jaiyankargupta** [comment]
@MaulikGupta27 done
