### ISSUE TITLE
Mention LEGAL STUFFS in footer section and SEARCH BAR in nav. section

### ISSUE THREAD

**Issue by Kumkummm-20** [Mohak1809/OCD-Website#37]
Footer section of the website must contain LEGAL stuffs which explains what information your website collects from visitors and how it’s used .
These includes :

- Copyright Notice
- Privacy Policy
- DMCA Policy

Search Bar allows the users to input keywords or phrases to search for specific information.
It Reduces bounce/exit rates.

- create a search bar in nav section in HTML page
- style it with CSS with a logo of magnifying glass.
- make it responsive .
- use JS to allow search.

**Comment by NikhilByteSmith** [comment]
@Mohak1809 please assign this issue to me.

**Comment by jaiyankargupta** [comment]
@NikhilByteSmith done
