### ISSUE TITLE
bugs in about us section 

### ISSUE THREAD

**Issue by ANUBHAVDIXIT2004** [Mohak1809/OCD-Website#372]
navbar in about section is showing bugs :
![Screenshot (14)](https://github.com/user-attachments/assets/2d23e41c-dad7-4bb7-9123-aa40a754d449)

**Comment by ANUBHAVDIXIT2004** [comment]
@jaiyankargupta pls assign this to me sir

**Comment by jaiyankargupta** [comment]
@ANUBHAVDIXIT2004
