### ISSUE TITLE
Button not working on homepage

### ISSUE THREAD

**Issue by MaulikGupta27** [Mohak1809/OCD-Website#38]
The "Submit" button on the homepage doesn't work when clicked.

**Steps to Reproduce:**
1. Go to the homepage.
2. Click the "Submit" button.

**Expected Behavior:**
The form should be submitted.

**Actual Behavior:**
Nothing happens when the button is clicked.

**Comment by Palak565** [comment]
@jaiyankargupta Please assign this issue to me

**Comment by jaiyankargupta** [comment]
@Palak565 done
