### ISSUE TITLE
Add Languages

### ISSUE THREAD

**Issue by PiyushRaj-7699** [Mohak1809/OCD-Website#39]
We can add different languages so that User can read and understand the OCD in their own language.

- We will write about our website in 4-5 different languages (like - Hindi, English(default), Marathi, Telugu, etc..)
- Asking a prompt message from the user, in which language he/ she is comfortable.
- User can switch the language whenever he/she wants.

**Comment by Kumkummm-20** [comment]
@jaiyankargupta sir please assign this issue to me.

**Comment by jaiyankargupta** [comment]
@Kumkummm-20 done
