### ISSUE TITLE
Missing Favicon and OCD Logo in footer

### ISSUE THREAD

**Issue by Tanisha020** [Mohak1809/OCD-Website#399]
Add favicon and footer logo to the OCD-30DaysOfJs page

![image](https://github.com/user-attachments/assets/d10a03c5-18de-4be2-912b-18392ba773e7)

**Comment by Tanisha020** [comment]
@jaiyankargupta please assign this issue to me.

**Comment by jaiyankargupta** [comment]
@Tanisha020 done
