### ISSUE TITLE
Implementation of a Resource library

### ISSUE THREAD

**Issue by SnehaChauhan1174** [Mohak1809/OCD-Website#41]
Develop a section where users can access a library of coding resources, including tutorials, docs, and project ideas.

1. Design the resource library interface
2. Create a database for storing resources
3. Implement search 
4. Filter functionality.

**Comment by NavvneetK** [comment]
@jaiyankargupta assign this issue to me

**Comment by jaiyankargupta** [comment]
@NavvneetK done

**Comment by rajveerpathak1** [comment]
Assign this to me

**Comment by Mohak1809** [comment]
@rajveerpathak1 done👍
