### ISSUE TITLE
Add a separate projects section

### ISSUE THREAD

**Issue by NikhilByteSmith** [Mohak1809/OCD-Website#43]
in this section, we can display all the ongoing projects by ocd with their description and repo links so those who are interested can contribute to them.

Steps:

- make basic HTML for the page which has cards that can be duplicated with a placeholder for images 
- add css styles

something similar to the images below

![image](https://github.com/user-attachments/assets/0a26246b-21ff-4b38-b1f7-c0341dc0247d)
![image](https://github.com/user-attachments/assets/b87257a0-a8ee-4f23-92e4-58e64662132e)

**Comment by divyadahiya14** [comment]
@NikhilByteSmith please assign this issue to me

**Comment by divyadahiya14** [comment]
@jaiyankargupta sir please assign this issue to me

**Comment by jaiyankargupta** [comment]
@divyadahiya14 done
