### ISSUE TITLE
Add "Member Testimonials" Section to Showcase Positive Reviews

### ISSUE THREAD

**Issue by Tanisha020** [Mohak1809/OCD-Website#45]
### Details:

**Section Placement:** The "Member Testimonials" section should be prominently placed on the homepage, below the main banner, or on a dedicated page accessible from the main navigation menu.

**Content:** Display selected positive reviews and feedback from current and past members.

**Functionality:** Allow members to submit their testimonials through a simple form on the website.

**Benefits:**
- Builds trust and credibility with potential new members.
- Enhances member engagement by valuing and showcasing their feedback.
- Provides proof of the organization's positive impact and community.

**Comment by jaiyankargupta** [comment]
@jaiyankargupta please assign this issue.
