### ISSUE TITLE
Create a Dedicated Achievements Section on the Website

### ISSUE THREAD

**Issue by Sonia2105** [Mohak1809/OCD-Website#49]
To better showcase the club's accomplishments and milestones, we propose adding a dedicated "Achievements" section to the website. This section will highlight key achievements, awards, project milestones, and notable contributions from members. It will serve as a source of pride for current members and an attractive feature for potential new members. 

*Benefits*:
- Increases visibility of the club's successes.
- Encourages and motivates members by recognizing their efforts.
- Attracts new members and collaborators by showcasing the club's impact and achievements.

*Tasks*:
1. Design a layout for the Achievements section.
2. Collect and verify information about the club's achievements.
3. Regularly update the section with new milestones and accomplishments.
4. Ensure the section is easily accessible from the main navigation menu.

**Comment by paridhi-kapoor** [comment]
@jaiyankargupta please assign this task to me.

**Comment by jaiyankargupta** [comment]
@paridhi-kapoor done
