### ISSUE TITLE
Add OCD Logo,Header and Favicon

### ISSUE THREAD

**Issue by nototiger0227** [Mohak1809/OCD-Website#52]
1. The OCD logo must be added in the top Right Corner of the page.
2. A Header must be added that includes nav bar and Open Code Developer Society.
3.Favicon must be added.
![image](https://github.com/user-attachments/assets/6f041465-15b8-4d35-b3f4-9b05101e1372)

**Comment by NikhilByteSmith** [comment]
@Mohak1809 please assign this issue to me .

**Comment by raghzzzspace** [comment]
Sir pls assign this issue to me i would like to work on it. Thanks!

**Comment by jaiyankargupta** [comment]
@raghzzzspace done
