### ISSUE TITLE
Contact Number Input Issue

### ISSUE THREAD

**Issue by gagan-1307** [Mohak1809/OCD-Website#62]
**1. The contact number should take only integer input.
2. The input should be of 10 digits .
3. Add a country list to select country code before contact no.**

**Comment by yashika1221** [comment]
@jaiyankargupta Assign this task to me

**Comment by jaiyankargupta** [comment]
@yashika1221 done 👍

**Comment by yashika1221** [comment]
> @yashika1221 done 👍
Issue resolved and PR created

**Comment by jaiyankargupta** [comment]
@yashika1221 branch conflict resolve kro
