### ISSUE TITLE
Make Navbar Sticky and Page Highlighter

### ISSUE THREAD

**Issue by parvejsir** [Mohak1809/OCD-Website#64]
Make the Navbar Sticky or fixed i.e. if user scroll down but navbar section must be fixed with header.
And make page highlighter i.e. if user click on home section then home section will be underline or highlight,if user on about section then about section will be underline or highlight...and so on for all the section which present in navbar section.

**Comment by Priyankagarhwal** [comment]
@jaiyankargupta pls assign this issue to me

**Comment by jaiyankargupta** [comment]
@Priyankagarhwal done
