### ISSUE TITLE
Add 'About' Section

### ISSUE THREAD

**Issue by yashika1221** [Mohak1809/OCD-Website#66]
**The website should contain an About section which provides an overview to the user about the following :**

- An introduction to the OpenCode Developer Society.
- The working of the society.
- The aim and the future goals of the society.
- A highlight of the achievements and the credentials.
- Activities and workshops organised.

**Comment by nototiger0227** [comment]
@jaiyankargupta Please assign this issue to me

**Comment by jaiyankargupta** [comment]
@nototiger0227 done

**Comment by nototiger0227** [comment]
@jaiyankargupta issue solved and PR created.
