### ISSUE TITLE
Enhancement: Add Dark Mode Support

### ISSUE THREAD

**Issue by rajveerpathak1** [Mohak1809/OCD-Website#9]
--> Description
It would be great to have a dark mode option for the website. This would help users who prefer dark themes to reduce eye strain and improve the overall user experience.

--> Expected Behavior
When the dark mode is toggled on:
- The background should turn to a darker color.
- Text should become lighter to maintain readability.
- Other elements like buttons and borders should adjust to the dark theme.

--> Actual Behavior
Currently, there is no dark mode option available.

**Comment by DeadpoolX7** [comment]
I am willing to undertake this task and deliver the following requirements.

Assign me this task, asap.

**Comment by rishabhchaudhary2** [comment]
@Mohak1809 please assign me this task

**Comment by jaiyankargupta** [comment]
@rishabhchaudhary2 done

**Comment by jaiyankargupta** [comment]
@DeadpoolX7 go for another issue please
