### ISSUE TITLE
Enhancing the Website Background for an Engaging User Experience

### ISSUE THREAD

**Issue by Senpenn** [Mohak1809/OCD-Website#99]
to enhance the website,we can do:
1.we can use the hover effects to make the website more interactive with the users.
2.we can use high quality images and graphics to make it more visually appealing to the content 
3. we should ensure the images are optimized for fast loading times.

**Comment by Isham17NIT** [comment]
@jaiyankargupta please assign this issue to me.

**Comment by jaiyankargupta** [comment]
@Isham17NIT done
